### ISSUE TITLE
pod install and run-ios errors

### ISSUE THREAD

**Issue by veeracs** [fbsamples/f8app#101]
```
⚡ pod install
Analyzing dependencies
Fetching podspec for `CodePush` from `../node_modules/react-native-code-push`
Fetching podspec for `React` from `../node_modules/react-native`
Fetching podspec for `react-native-fbsdk` from `../node_modules/react-native-fbsdk/iOS`
[!] No podspec found for `react-native-fbsdk` in `../node_modules/react-native-fbsdk/iOS`
```

```
⚡ react-native run-ios
Found Xcode project F8v2.xcodeproj
Launching iPhone 6 (9.2)...
Building using "xcodebuild -project F8v2.xcodeproj -scheme F8v2 -destination id=2FEB21AD-FD88-4B2A-B0B4-5AB39520AF66 -derivedDataPath build"
User defaults from command line:
    IDEDerivedDataPathOverride = /Users/csekharveera/Sites/f8app/ios/build

=== BUILD TARGET BVLinearGradient OF PROJECT BVLinearGradient WITH CONFIGURATION Debug ===

Check dependencies

=== BUILD TARGET F8v2 OF PROJECT F8v2 WITH CONFIGURATION Debug ===

Check dependencies
The file “Pods-F8v2.debug.xcconfig” couldn’t be opened because there is no such file. (/Users/csekharveera/Sites/f8app/ios/Pods/Target Support Files/Pods-F8v2/Pods-F8v2.debug.xcconfig)

PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock build/Build/Intermediates/F8v2.build/Debug-iphonesimulator/F8v2.build/Script-BE0B165BA96102DAE4AF6D67.sh
    cd /Users/csekharveera/Sites/f8app/ios
    /bin/sh -c /Users/csekharveera/Sites/f8app/ios/build/Build/Intermediates/F8v2.build/Debug-iphonesimulator/F8v2.build/Script-BE0B165BA96102DAE4AF6D67.sh
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock build/Build/Intermediates/F8v2.build/Debug-iphonesimulator/F8v2.build/Script-BE0B165BA96102DAE4AF6D67.sh
(1 failure)
Installing build/Build/Products/Debug-iphonesimulator/F8v2.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
/Users/csekharveera/Sites/f8app/node_modules/react-native/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/F8v2.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:464:13)
    at Object.execFileSync (child_process.js:484:13)
    at _runIOS (/Users/csekharveera/Sites/f8app/node_modules/react-native/local-cli/runIOS/runIOS.js:82:32)
    at /Users/csekharveera/Sites/f8app/node_modules/react-native/local-cli/runIOS/runIOS.js:24:5
    at tryCallTwo (/Users/csekharveera/Sites/f8app/node_modules/react-native/node_modules/promise/lib/core.js:45:5)
    at doResolve (/Users/csekharveera/Sites/f8app/node_modules/react-native/node_modules/promise/lib/core.js:200:13)
    at new Promise (/Users/csekharveera/Sites/f8app/node_modules/react-native/node_modules/promise/lib/core.js:66:3)
    at Array.runIOS (/Users/csekharveera/Sites/f8app/node_modules/react-native/local-cli/runIOS/runIOS.js:23:10)
    at Object.run (/Users/csekharveera/Sites/f8app/node_modules/react-native/local-cli/cliEntry.js:96:13)
    at Object.<anonymous> (/Users/csekharveera/.nvm/versions/node/v4.2.6/lib/node_modules/react-native-cli/index.js:88:7)
```

**Comment by veeracs** [comment]
I went past that error by manually creating podspec under `../node_modules/react-native-fbsdk/iOS`

but now I'm getting another build error related to running `react-native run-ios`

```
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/csekharveera/Sites/f8app/ios/build/Build/Intermediates/Pods.build/Debug-iphonesimulator/react-native-fbsdk.build/Objects-normal/x86_64/RCTConvert+FBSDKSharingContent.o /Users/csekharveera/Sites/f8app/node_modules/react-native-fbsdk/iOS/RCTFBSDK/share/RCTConvert+FBSDKSharingContent.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Installing build/Build/Products/Debug-iphonesimulator/F8v2.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
/Users/csekharveera/Sites/f8app/node_modules/react-native/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/F8v2.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:464:13)
    at Object.execFileSync (child_process.js:484:13)
    at _runIOS (/Users/csekharveera/Sites/f8app/node_modules/react-native/local-cli/runIOS/runIOS.js:82:32)
    at /Users/csekharveera/Sites/f8app/node_modules/react-native/local-cli/runIOS/runIOS.js:24:5
    at tryCallTwo (/Users/csekharveera/Sites/f8app/node_modules/react-native/node_modules/promise/lib/core.js:45:5)
    at doResolve (/Users/csekharveera/Sites/f8app/node_modules/react-native/node_modules/promise/lib/core.js:200:13)
    at new Promise (/Users/csekharveera/Sites/f8app/node_modules/react-native/node_modules/promise/lib/core.js:66:3)
    at Array.runIOS (/Users/csekharveera/Sites/f8app/node_modules/react-native/local-cli/runIOS/runIOS.js:23:10)
    at Object.run (/Users/csekharveera/Sites/f8app/node_modules/react-native/local-cli/cliEntry.js:96:13)
    at Object.<anonymous> (/Users/csekharveera/.nvm/versions/node/v4.2.6/lib/node_modules/react-native-cli/index.js:88:7)
```

**Comment by adebree** [comment]
Same issue here. I was able to get around the podspec issue by installing react-native-fbsdk via rnpm:

```
npm install rnpm -g
rnpm install react-native-fbsdk
```

**Comment by adebree** [comment]
And the 

```
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

issue was 'fixed' by running a 

```
react-native upgrade
```

But I know end up with an error in the ios simulator being:

```
Native module cannot be null.
```

And in the packager output:

```
NotFoundError: Cannot find entry file global code@http://localhost:8081/index.ios.js in any of the roots: ["/Users/arne/04.Projects/react-native/f8app"]
    at DependencyGraph._getAbsolutePath (/Users/arne/04.Projects/react-native/f8app/node_modules/node-haste/lib/index.js:288:13)
    at /Users/arne/04.Projects/react-native/f8app/node_modules/node-haste/lib/index.js:226:30
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

So far unable to figure out why / what this is...

**Comment by frantic** [comment]
This was a problem with [`react-native-fbsdk`](https://github.com/facebook/react-native-fbsdk), the podspec was missing. Should be fixed now, I'll upgrade package.json soon.

**Comment by prcolaco** [comment]
Still same issue with pod install... And no rnpm to solve it now. Ideas?

Already tried to install newer versions 0.4.0 and 0.5.0 of react-native-fbsdk, but no luck, still missing the podspec...

**Comment by prcolaco** [comment]
Just found the problem...

I am using a case sensitive filesystem and in the Podfile react-native-fbsdk/iOS is with caps letters instead of ios lowercase. Changed and it works. Will submit pull request soon...
